using System.Text;

namespace Consultologist.PackageFormat;

/// <summary>
/// Derives a Mermaid flowchart from a manifest's nodes. Bindings are the edges plus
/// strictly more, so the diagram is always generated and never authored — the
/// derived-view rule that rejected a second edge file. forEach chains render as a
/// per-collection subgraph: the container lives on as presentation, never as format
/// (external/consultologist-package-format/package-format-v5.md). The checked-in
/// The general package's dag.mmd (consultologist-workflows repo) is generated by this generator.
/// </summary>
public static class WorkflowDagDiagram
{
    public static string Generate(WorkflowPackageManifest manifest)
    {
        var nodes = manifest.Nodes
            ?? throw new InvalidOperationException(
                $"Package {manifest.Name}@{manifest.Version} declares no nodes; the DAG diagram requires specVersion 5.");

        var sb = new StringBuilder();
        sb.Append("flowchart TD\n");

        // External sources first, in first-reference order: engine inputs, scalar
        // data entries, and forEach collections all render as stadiums.
        foreach (var source in CollectExternalSources(manifest))
        {
            sb.Append($"    {Sanitize(source)}([\"{source}\"])\n");
        }

        sb.Append('\n');

        var nodesById = nodes.ToDictionary(node => node.Id, StringComparer.Ordinal);

        foreach (var node in nodes.Where(node => node.ForEach is null))
        {
            if (node.Aggregate != null)
            {
                // Aggregators are graph-visible by construction: their own box, one
                // labeled edge per source in declared order (v6, aggregator nodes).
                sb.Append($"    {Sanitize(node.Id)}[\"{node.Id}<br/>{node.Label}<br/>aggregate\"]\n");

                foreach (var sourceRef in node.Aggregate)
                {
                    var sourceId = sourceRef.StartsWith(WorkflowNodeBindingSources.NodePrefix, StringComparison.Ordinal)
                        ? sourceRef[WorkflowNodeBindingSources.NodePrefix.Length..]
                        : sourceRef;
                    sb.Append($"    {Sanitize(sourceId)} -->|\"aggregate\"| {Sanitize(node.Id)}\n");
                }

                continue;
            }

            var label = $"{node.Id}<br/>{node.Label}";
            if (node.Output != null)
            {
                label += $"<br/>output: {node.Output.Schema}";
            }

            sb.Append($"    {Sanitize(node.Id)}[\"{label}\"]\n");

            foreach (var (variable, binding) in node.Bindings ?? new Dictionary<string, WorkflowBindingValue>())
            {
                AppendEdge(sb, binding, variable, Sanitize(node.Id), indent: "    ");
            }
        }

        foreach (var collection in nodes
            .Where(node => node.ForEach != null)
            .Select(node => node.ForEach!)
            .Distinct(StringComparer.Ordinal))
        {
            var chain = nodes.Where(node => string.Equals(node.ForEach, collection, StringComparison.Ordinal)).ToList();
            var subgraphId = "foreach_" + Sanitize(collection);

            bool IsItemAligned(WorkflowBindingValue binding) =>
                binding.From.StartsWith(WorkflowNodeBindingSources.NodePrefix, StringComparison.Ordinal)
                && nodesById.TryGetValue(binding.From[WorkflowNodeBindingSources.NodePrefix.Length..], out var target)
                && string.Equals(target.ForEach, collection, StringComparison.Ordinal);

            sb.Append('\n');
            sb.Append($"    {Sanitize(collection)} -->|\"forEach\"| {subgraphId}\n");
            sb.Append($"    subgraph {subgraphId}[\"per {collection} item\"]\n");

            foreach (var node in chain)
            {
                var itemFields = (node.Bindings ?? new Dictionary<string, WorkflowBindingValue>())
                    .Values
                    .Where(binding => binding.From.StartsWith("item:", StringComparison.Ordinal))
                    .Select(binding => binding.From["item:".Length..])
                    .Distinct(StringComparer.Ordinal)
                    .ToList();
                var label = $"{node.Id}<br/>{node.Label}";
                if (itemFields.Count > 0)
                {
                    label += $"<br/>item: {string.Join(", ", itemFields)}";
                }

                sb.Append($"        {Sanitize(node.Id)}[\"{label}\"]\n");
            }

            // Item-aligned edges (same-collection node: bindings) live inside the box.
            foreach (var node in chain)
            {
                foreach (var (variable, binding) in node.Bindings ?? new Dictionary<string, WorkflowBindingValue>())
                {
                    if (IsItemAligned(binding))
                    {
                        AppendEdge(sb, binding, variable, Sanitize(node.Id), indent: "        ");
                    }
                }
            }

            sb.Append("    end\n");

            // Broadcast and input edges cross the boundary from outside, keeping the
            // subgraph box tight.
            foreach (var node in chain)
            {
                foreach (var (variable, binding) in node.Bindings ?? new Dictionary<string, WorkflowBindingValue>())
                {
                    if (!IsItemAligned(binding))
                    {
                        AppendEdge(sb, binding, variable, Sanitize(node.Id), indent: "    ");
                    }
                }
            }
        }

        AppendDeliverables(sb, manifest);

        return sb.ToString();
    }

    /// <summary>
    /// The result set, as its own terminal shape (#353). Without this the
    /// diagram cannot say which aggregator is a deliverable — and for v8 it
    /// cannot say that a deliverable is conditional, in a format whose whole
    /// point is that some of them are not always produced.
    ///
    /// A condition renders as a dotted edge from the input it reads, because
    /// that edge is a predicate rather than data flow: nothing of the input's
    /// value travels along it.
    /// </summary>
    private static void AppendDeliverables(StringBuilder sb, WorkflowPackageManifest manifest)
    {
        var deliverables = Deliverables(manifest);

        if (deliverables.Count == 0)
        {
            return;
        }

        sb.Append('\n');

        foreach (var (id, label, nodeRef, when) in deliverables)
        {
            var boxId = id is null ? "result" : $"result_{Sanitize(id)}";
            var caption = id is null ? "result" : $"{id}<br/>{label}";

            // Hexagon: distinct from a node's rectangle and a source's stadium,
            // so a deliverable never reads as one more aggregator.
            sb.Append($"    {boxId}{{{{\"{caption}\"}}}}\n");

            var nodeId = nodeRef.StartsWith(WorkflowNodeBindingSources.NodePrefix, StringComparison.Ordinal)
                ? nodeRef[WorkflowNodeBindingSources.NodePrefix.Length..]
                : nodeRef;
            sb.Append($"    {Sanitize(nodeId)} --> {boxId}\n");

            if (when is null)
            {
                continue;
            }

            // Unparseable conditions cannot reach a published package — the
            // validator parses the same grammar — but the diagram is generated
            // for drafts too, so the raw text is drawn rather than dropped.
            if (!WorkflowResultConditions.TryParse(when, out var condition, out _) || condition is null)
            {
                sb.Append($"    {boxId} -.->|\"when {when}\"| {boxId}\n");
                continue;
            }

            // v9: the operand's suffix says which form — ".age >= 65", "count > 1".
            var suffix = condition.IsCount ? "count " : condition.Field is null ? string.Empty : $".{condition.Field} ";
            var test = condition.Literal is null
                ? $"when {suffix}true"
                : $"when {suffix}{condition.Operator} {condition.Literal}";

            sb.Append($"    {Sanitize($"input:{condition.InputId}")} -.->|\"{test}\"| {boxId}\n");
        }
    }

    /// <summary>
    /// Both result shapes as one list: v7's declared entries, or v6's single
    /// string, which carries neither an id nor a label.
    /// </summary>
    private static IReadOnlyList<(string? Id, string? Label, string Node, string? When)> Deliverables(
        WorkflowPackageManifest manifest)
    {
        if (manifest.Results is { Count: > 0 })
        {
            return manifest.Results
                .Select(result => ((string?)result.Id, (string?)result.Label, result.Node, result.When))
                .ToList();
        }

        return manifest.Result is { } single
            ? new[] { ((string?)null, (string?)null, single, (string?)null) }
            : Array.Empty<(string?, string?, string, string?)>();
    }

    private static void AppendEdge(
        StringBuilder sb,
        WorkflowBindingValue binding,
        string variable,
        string targetId,
        string indent)
    {
        string sourceId;

        if (binding.From.StartsWith(WorkflowNodeBindingSources.NodePrefix, StringComparison.Ordinal))
        {
            sourceId = Sanitize(binding.From[WorkflowNodeBindingSources.NodePrefix.Length..]);
        }
        else if (binding.From.StartsWith("input:", StringComparison.Ordinal)
            || binding.From.StartsWith(WorkflowNodeBindingSources.DataPrefix, StringComparison.Ordinal))
        {
            sourceId = Sanitize(binding.From);
        }
        else
        {
            return; // item:* fields live in the node label.
        }

        var label = binding.As is null ? variable : $"{variable} (as {binding.As})";
        sb.Append($"{indent}{sourceId} -->|\"{label}\"| {targetId}\n");
    }

    private static IReadOnlyList<string> CollectExternalSources(WorkflowPackageManifest manifest)
    {
        var nodes = manifest.Nodes ?? new List<WorkflowNodeSpec>();
        var sources = new List<string>();

        void Add(string? from)
        {
            if (from != null
                && (from.StartsWith("input:", StringComparison.Ordinal) || from.StartsWith(WorkflowNodeBindingSources.DataPrefix, StringComparison.Ordinal))
                && !sources.Contains(from))
            {
                sources.Add(from);
            }
        }

        foreach (var node in nodes)
        {
            foreach (var binding in (node.Bindings ?? new Dictionary<string, WorkflowBindingValue>()).Values)
            {
                Add(binding.From);
            }

            Add(node.ForEach);
        }

        // #353: an input only a condition reads is bound by nothing, so the
        // loop above never sees it — and it would be missing from the diagram
        // of the very package whose deliverables turn on it. Added after the
        // bound sources so a package with no conditions draws exactly as before.
        foreach (var result in manifest.Results ?? new List<WorkflowResultSpec>())
        {
            if (result.When != null
                && WorkflowResultConditions.TryParse(result.When, out var condition, out _)
                && condition != null)
            {
                Add($"input:{condition.InputId}");
            }
        }

        return sources;
    }

    private static string Sanitize(string raw)
        => new(raw.Select(c => char.IsLetterOrDigit(c) ? c : '_').ToArray());
}
